version: '3.9'
services:
  ecommerce-catalog:
    build: ./ecommerce-catalog/
    ports:
      - "8081:8081"
  ecommerce-checkout:
    build: ./ecommerce-checkout/
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - ~/tmp/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=testdb